### ISSUE TITLE
Gamma calibration

### ISSUE THREAD

**Issue by sumiya-kuroda** [zhuangjun1981/WarpedVisualStim#2]
Hello @zhuangjun1981 !

My name is Sumiya Kuroda, and I am a PhD student at Sainsbury Wellcome Centre. I am working on implementing your code for visual stimuli into our 2p imaging setup.

Do you correct gamma for the monitors? If so, how do you do? Do you use PsychoPy's function? Do you use Thorlabs' photodetector that you are probably using for the square Indicator?

**Comment by zhuangjun1981** [comment]
Hey Sumiya, Thank you for reaching out.  

For your questions:
1. When I was doing visual physiology experiments, I used the [gamma correction](https://www.psychopy.org/general/gamma.html) builtin in the [monitor](https://psychopy.org/api/monitors.html) class in [psychopy](https://psychopy.org/index.html) library. The WarpedVisualStim does not have gamma correction by itself. But it can use saved psychopy gamma correction [here](https://github.com/zhuangjun1981/WarpedVisualStim/blob/89077ca58ca0a2e509606102932510c31ee23901/WarpedVisualStim/MonitorSetup.py#L74C19-L75C34). 
2. I used thorlabs photodiode, something like [this](https://www.thorlabs.com/newgrouppage9.cfm?objectgroup_id=3257), make sure it is in the right spectrum and have enough temporal resolution.

**Comment by sumiya-kuroda** [comment]
Thanks so much! Very helpful information!
